### ISSUE TITLE
owncloud TODO

### ISSUE THREAD

**Issue by yan12125** [yan12125/macports-overlay#1]
- [ ] owncloudcmd symlink to /opt/local/bin
- [ ] built-in update check doesn't work correctly
- [ ] install dylibs inside owncloud.app/MacOS?
